### ISSUE TITLE
error when try create project

### ISSUE THREAD

**Issue by jessecogollo** [PatrickWolleb/generator-koa-rest#2]
steps:
1) execute: yo koa-rest
2) I write name and URL doc.
then terminal show this message:
events.js:141
      throw er; // Unhandled 'error' event
            ^
AssertionError: Trying to copy from a source that does not exist: /usr/local/lib/node_modules/generator-koa-rest/app/templates/.buildignore
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-koa-rest/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:44:3)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-koa-rest/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:22:17)
    at module.exports.yeoman.generators.Base.extend.writing.projectfiles (/usr/local/lib/node_modules/generator-koa-rest/app/index.js:59:15)
    at /usr/local/lib/node_modules/generator-koa-rest/node_modules/yeoman-generator/lib/base.js:409:16
    at processImmediate [as _immediateCallback](timers.js:368:17)

I am using 
- iojs 1.8
- yeoman 1.4.6
- npm 2.9.0

**Comment by anthonybarsotti** [comment]
I'm having the same problem.

**Comment by PatrickWolleb** [comment]
https://github.com/npm/npm/issues/3763

**Comment by PatrickWolleb** [comment]
Ok it seems npm publish removes .gitignore files :s. I have not found a workaround to include them. But current fix omits them completely. Fixed in 1.1.7
